name: Automated Builds

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - build.gradle
      - build.gradle.kts
      - gradle.properties
      - settings.gradle
      - gradle/**
      - gradlew
      - gradlew.bat
      - versioning.gradle
      - .github/workflows/publish.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build Maven Repository
        run: ./gradlew publishAllPublicationsToLocalMavenRepository

      - name: Clone target Codeberg repository
        run: |
            # Clone ONLY the maven branch
            git clone -b maven --single-branch https://${{ secrets.CODEBERG_TOKEN }}@codeberg.org/vmbbi/pages.git target-repo

            cd target-repo
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
          
            git fetch origin master:refs/remotes/origin/master
            git merge origin/master --no-edit

      - name: Copy build artifacts and push to Codeberg
        run: |
                cp -R build/repo/* target-repo/
                cd target-repo
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                if ! git diff --cached --quiet; then
                  git commit -m "chore: publish artifacts [skip ci]"
                  # Push specifically back to the maven branch
                  git push origin HEAD:maven
                else
                  echo "No changes to commit."
                fi